# Generated by Django 5.0.2 on 2024-05-17 16:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file', '0001_initial'),
        ('like', '0001_initial'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExhibitionLike',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('like', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='like.like')),
            ],
            options={
                'db_table': 'tbl_exhibition_like',
            },
        ),
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('exhibition_title', models.CharField(max_length=40)),
                ('exhibition_content', models.CharField(max_length=2000)),
                ('exhibition_status', models.BooleanField(default=True)),
                ('exhibition_post_status', models.BooleanField(default=True)),
                ('exhibition_url', models.TextField()),
                ('exhibition_view_count', models.IntegerField(default=0)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.school')),
            ],
            options={
                'db_table': 'tbl_exhibition',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ExhibitionFile',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='file.file')),
                ('path', models.ImageField(upload_to='exhibition/%Y/%m/%d')),
                ('download_path', models.ImageField(upload_to='exhibition_down/%Y/%m/%d')),
                ('preview', models.BooleanField(default=False)),
                ('exhibition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exhibition.exhibition')),
            ],
            options={
                'db_table': 'tbl_exhibition_file',
            },
        ),
    ]
