# Generated by Django 5.0.2 on 2024-05-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='exhibition_content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='exhibition_title',
            field=models.TextField(),
        ),
    ]
