# Generated by Django 5.0.2 on 2024-05-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='community_content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='community',
            name='community_title',
            field=models.TextField(),
        ),
    ]
