# Generated by Django 5.0.2 on 2024-05-17 16:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('tag_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_tag',
                'ordering': ['created_date'],
            },
        ),
    ]
