# Generated by Django 5.0.2 on 2024-05-17 16:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file', '0001_initial'),
        ('like', '0001_initial'),
        ('tag', '0001_initial'),
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('onelab_main_title', models.CharField(max_length=30)),
                ('onelab_content', models.CharField(max_length=100)),
                ('onelab_detail_content', models.CharField(max_length=2000)),
                ('onelab_url', models.CharField(default='http://localhost:', max_length=300)),
                ('onelab_max_count', models.SmallIntegerField(default=2, max_length=10)),
                ('onelab_ask_email', models.CharField(max_length=300)),
                ('onelab_status', models.BooleanField(default=True)),
                ('onelab_post_status', models.BooleanField(default=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tag.tag')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='university.university')),
            ],
            options={
                'db_table': 'tbl_onelab',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='OneLabBannerFile',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='file.file')),
                ('path', models.ImageField(upload_to='onelab_banner/%Y/%m/%d')),
                ('onelab', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='onelab.onelab')),
            ],
            options={
                'db_table': 'tbl_onelab_banner_file',
            },
        ),
        migrations.CreateModel(
            name='OneLabFile',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='file.file')),
                ('path', models.ImageField(upload_to='onelab/%Y/%m/%d')),
                ('onelab', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='onelab.onelab')),
            ],
            options={
                'db_table': 'tbl_onelab_file',
            },
        ),
        migrations.CreateModel(
            name='OneLabLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('like', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='like.like')),
            ],
            options={
                'db_table': 'tbl_onelab_like',
            },
        ),
    ]
