# Generated by Django 5.0.2 on 2024-05-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onelab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onelab',
            name='onelab_content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='onelab',
            name='onelab_detail_content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='onelab',
            name='onelab_main_title',
            field=models.TextField(),
        ),
    ]
