# Generated by Django 5.0.2 on 2024-05-17 16:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighSchool',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('high_school_member_birth', models.DateField(default='2008-01-01')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='member.member')),
            ],
            options={
                'db_table': 'tbl_high_school',
                'ordering': ['-created_date'],
            },
        ),
    ]
